import mongoose from 'mongoose';
import { config } from './config/index.js';
import User from './models/User.js';
import Property from './models/Property.js';

// Sample properties data
const sampleProperties = [
  {
    title: 'Luxury Villa in Riyadh',
    titleAr: 'فيلا فاخرة في الرياض',
    description:
      'Beautiful 5-bedroom villa with private pool, garden, and modern amenities. Located in the prestigious Al Olaya district.',
    descriptionAr:
      'فيلا جميلة من 5 غرف نوم مع مسبح خاص وحديقة ومرافق حديثة. تقع في حي العليا المرموق.',
    type: 'villa',
    category: 'residential',
    status: 'for_sale',
    price: 2500000,
    currency: 'SAR',
    area: 450,
    bedrooms: 5,
    bathrooms: 4,
    location: {
      address: 'Al Olaya District',
      addressAr: 'حي العليا',
      city: 'Riyadh',
      cityAr: 'الرياض',
      country: 'Saudi Arabia',
      countryAr: 'السعودية',
      coordinates: { type: 'Point', coordinates: [46.6753, 24.7136] },
    },
    images: ['https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800'],
    features: ['Pool', 'Garden', 'Garage', 'Smart Home', 'Security System'],
    featuresAr: ['مسبح', 'حديقة', 'كراج', 'منزل ذكي', 'نظام أمان'],
    isFeatured: true,
  },
  {
    title: 'Modern Apartment in Jeddah',
    titleAr: 'شقة حديثة في جدة',
    description:
      'Stunning sea view apartment with 3 bedrooms. Features modern finishes and access to building amenities.',
    descriptionAr: 'شقة مطلة على البحر مع 3 غرف نوم. تتميز بتشطيبات حديثة ووصول إلى مرافق المبنى.',
    type: 'apartment',
    category: 'residential',
    status: 'for_rent',
    price: 8000,
    currency: 'SAR',
    area: 180,
    bedrooms: 3,
    bathrooms: 2,
    location: {
      address: 'Corniche Road',
      addressAr: 'طريق الكورنيش',
      city: 'Jeddah',
      cityAr: 'جدة',
      country: 'Saudi Arabia',
      countryAr: 'السعودية',
      coordinates: { type: 'Point', coordinates: [39.1728, 21.5433] },
    },
    images: ['https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800'],
    features: ['Sea View', 'Gym', 'Parking', 'Concierge', 'Balcony'],
    featuresAr: ['إطلالة بحرية', 'صالة رياضية', 'موقف سيارات', 'خدمة استقبال', 'شرفة'],
    isFeatured: true,
  },
  {
    title: 'Office Space in KAFD',
    titleAr: 'مكتب في كافد',
    description:
      'Premium office space in the King Abdullah Financial District. Perfect for businesses looking for a prestigious address.',
    descriptionAr:
      'مساحة مكتبية متميزة في مركز الملك عبدالله المالي. مثالية للشركات التي تبحث عن عنوان مرموق.',
    type: 'office',
    category: 'commercial',
    status: 'for_rent',
    price: 15000,
    currency: 'SAR',
    area: 250,
    location: {
      address: 'King Abdullah Financial District',
      addressAr: 'مركز الملك عبدالله المالي',
      city: 'Riyadh',
      cityAr: 'الرياض',
      country: 'Saudi Arabia',
      countryAr: 'السعودية',
      coordinates: { type: 'Point', coordinates: [46.6396, 24.7648] },
    },
    images: ['https://images.unsplash.com/photo-1497366216548-37526070297c?w=800'],
    features: ['Meeting Rooms', '24/7 Access', 'Parking', 'High-Speed Internet', 'Reception'],
    featuresAr: [
      'قاعات اجتماعات',
      'دخول على مدار الساعة',
      'موقف سيارات',
      'إنترنت عالي السرعة',
      'استقبال',
    ],
    isFeatured: true,
  },
  {
    title: 'Land Plot in Al Khobar',
    titleAr: 'أرض في الخبر',
    description:
      'Prime residential land plot in Al Khobar. Ideal for building your dream home or investment.',
    descriptionAr: 'قطعة أرض سكنية متميزة في الخبر. مثالية لبناء منزل أحلامك أو الاستثمار.',
    type: 'land',
    category: 'residential',
    status: 'for_sale',
    price: 800000,
    currency: 'SAR',
    area: 600,
    location: {
      address: 'Al Rawabi District',
      addressAr: 'حي الروابي',
      city: 'Al Khobar',
      cityAr: 'الخبر',
      country: 'Saudi Arabia',
      countryAr: 'السعودية',
      coordinates: { type: 'Point', coordinates: [50.2083, 26.2794] },
    },
    images: ['https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800'],
    features: ['Corner Plot', 'Near Schools', 'Near Mosque', 'Paved Roads'],
    featuresAr: ['قطعة زاوية', 'قرب المدارس', 'قرب المسجد', 'شوارع مسفلتة'],
    isFeatured: false,
  },
  {
    title: 'Warehouse in Dammam Industrial',
    titleAr: 'مستودع في دمام الصناعية',
    description:
      'Large warehouse facility with loading docks and office space. Perfect for logistics operations.',
    descriptionAr: 'مستودع كبير مع أرصفة تحميل ومساحة مكتبية. مثالي لعمليات الخدمات اللوجستية.',
    type: 'warehouse',
    category: 'industrial',
    status: 'for_rent',
    price: 25000,
    currency: 'SAR',
    area: 2000,
    location: {
      address: 'Second Industrial City',
      addressAr: 'المدينة الصناعية الثانية',
      city: 'Dammam',
      cityAr: 'الدمام',
      country: 'Saudi Arabia',
      countryAr: 'السعودية',
      coordinates: { type: 'Point', coordinates: [50.0028, 26.3927] },
    },
    images: ['https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=800'],
    features: ['Loading Docks', 'Office Space', 'High Ceiling', '24/7 Security', 'Fire System'],
    featuresAr: ['أرصفة تحميل', 'مساحة مكتبية', 'سقف عالي', 'أمان على مدار الساعة', 'نظام إطفاء'],
    isFeatured: false,
  },
  {
    title: 'Penthouse in King Abdullah Economic City',
    titleAr: 'بنتهاوس في مدينة الملك عبدالله الاقتصادية',
    description:
      'Exclusive penthouse with panoramic views. Features private terrace, jacuzzi, and premium finishes.',
    descriptionAr: 'بنتهاوس حصري مع إطلالات بانورامية. يتميز بتراس خاص وجاكوزي وتشطيبات فاخرة.',
    type: 'apartment',
    category: 'residential',
    status: 'for_sale',
    price: 3500000,
    currency: 'SAR',
    area: 350,
    bedrooms: 4,
    bathrooms: 5,
    location: {
      address: 'Bay La Sun',
      addressAr: 'باي لاسن',
      city: 'King Abdullah Economic City',
      cityAr: 'مدينة الملك عبدالله الاقتصادية',
      country: 'Saudi Arabia',
      countryAr: 'السعودية',
      coordinates: { type: 'Point', coordinates: [39.1282, 22.4532] },
    },
    images: ['https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800'],
    features: ['Private Terrace', 'Jacuzzi', 'Smart Home', 'Private Elevator', 'Sea View'],
    featuresAr: ['تراس خاص', 'جاكوزي', 'منزل ذكي', 'مصعد خاص', 'إطلالة بحرية'],
    isFeatured: true,
  },
  // Additional properties
  {
    title: 'Cozy Studio in Al Malaz',
    titleAr: 'استوديو مريح في الملز',
    description:
      'Perfect starter apartment with modern kitchen and bathroom. Close to public transport and shopping.',
    descriptionAr: 'شقة مثالية للمبتدئين مع مطبخ وحمام حديث. قريبة من وسائل النقل العام والتسوق.',
    type: 'apartment',
    category: 'residential',
    status: 'for_rent',
    price: 2500,
    currency: 'SAR',
    area: 45,
    bedrooms: 1,
    bathrooms: 1,
    location: {
      address: 'Al Malaz District',
      addressAr: 'حي الملز',
      city: 'Riyadh',
      cityAr: 'الرياض',
      country: 'Saudi Arabia',
      countryAr: 'السعودية',
      coordinates: { type: 'Point', coordinates: [46.7219, 24.6748] },
    },
    images: ['https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800'],
    features: ['Furnished', 'AC', 'Kitchen', 'Near Metro'],
    featuresAr: ['مفروش', 'مكيف', 'مطبخ', 'قرب المترو'],
    isFeatured: false,
  },
  {
    title: 'Family Villa in Al Nakheel',
    titleAr: 'فيلا عائلية في النخيل',
    description:
      'Spacious family villa with 6 bedrooms, large garden, and swimming pool. Perfect for large families.',
    descriptionAr: 'فيلا عائلية واسعة مع 6 غرف نوم وحديقة كبيرة ومسبح. مثالية للعائلات الكبيرة.',
    type: 'villa',
    category: 'residential',
    status: 'for_sale',
    price: 4200000,
    currency: 'SAR',
    area: 650,
    bedrooms: 6,
    bathrooms: 5,
    location: {
      address: 'Al Nakheel District',
      addressAr: 'حي النخيل',
      city: 'Riyadh',
      cityAr: 'الرياض',
      country: 'Saudi Arabia',
      countryAr: 'السعودية',
      coordinates: { type: 'Point', coordinates: [46.6289, 24.7743] },
    },
    images: ['https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800'],
    features: ['Pool', 'Garden', 'Maid Room', 'Driver Room', 'Garage'],
    featuresAr: ['مسبح', 'حديقة', 'غرفة خادمة', 'غرفة سائق', 'كراج'],
    isFeatured: true,
  },
  {
    title: 'Commercial Building in Olaya',
    titleAr: 'مبنى تجاري في العليا',
    description:
      'Prime commercial building with multiple floors. Excellent location for retail or office use.',
    descriptionAr: 'مبنى تجاري متميز متعدد الطوابق. موقع ممتاز للبيع بالتجزئة أو المكاتب.',
    type: 'building',
    category: 'commercial',
    status: 'for_sale',
    price: 15000000,
    currency: 'SAR',
    area: 3500,
    location: {
      address: 'Olaya Street',
      addressAr: 'شارع العليا',
      city: 'Riyadh',
      cityAr: 'الرياض',
      country: 'Saudi Arabia',
      countryAr: 'السعودية',
      coordinates: { type: 'Point', coordinates: [46.685, 24.6916] },
    },
    images: ['https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=800'],
    features: ['Elevator', 'Parking', 'Central AC', 'Security', 'Reception'],
    featuresAr: ['مصعد', 'موقف سيارات', 'تكييف مركزي', 'أمن', 'استقبال'],
    isFeatured: true,
  },
  {
    title: 'Beachfront Chalet in Half Moon Bay',
    titleAr: 'شاليه على البحر في خليج نصف القمر',
    description: 'Stunning beachfront chalet with direct beach access. Perfect weekend getaway.',
    descriptionAr: 'شاليه رائع على الشاطئ مع وصول مباشر للبحر. مثالي لعطلة نهاية الأسبوع.',
    type: 'villa',
    category: 'residential',
    status: 'for_rent',
    price: 5000,
    currency: 'SAR',
    area: 200,
    bedrooms: 3,
    bathrooms: 2,
    location: {
      address: 'Half Moon Bay',
      addressAr: 'خليج نصف القمر',
      city: 'Al Khobar',
      cityAr: 'الخبر',
      country: 'Saudi Arabia',
      countryAr: 'السعودية',
      coordinates: { type: 'Point', coordinates: [50.0567, 26.1833] },
    },
    images: ['https://images.unsplash.com/photo-1499793983690-e29da59ef1c2?w=800'],
    features: ['Beach Access', 'BBQ Area', 'Furnished', 'Parking'],
    featuresAr: ['وصول للشاطئ', 'منطقة شواء', 'مفروش', 'موقف سيارات'],
    isFeatured: false,
  },
  {
    title: 'Luxury Apartment in Diplomatic Quarter',
    titleAr: 'شقة فاخرة في الحي الدبلوماسي',
    description: 'High-end apartment in the prestigious Diplomatic Quarter with premium amenities.',
    descriptionAr: 'شقة راقية في الحي الدبلوماسي المرموق مع مرافق متميزة.',
    type: 'apartment',
    category: 'residential',
    status: 'for_rent',
    price: 18000,
    currency: 'SAR',
    area: 280,
    bedrooms: 4,
    bathrooms: 3,
    location: {
      address: 'Diplomatic Quarter',
      addressAr: 'الحي الدبلوماسي',
      city: 'Riyadh',
      cityAr: 'الرياض',
      country: 'Saudi Arabia',
      countryAr: 'السعودية',
      coordinates: { type: 'Point', coordinates: [46.6162, 24.6856] },
    },
    images: ['https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800'],
    features: ['Compound', 'Pool', 'Gym', 'Tennis Court', '24/7 Security'],
    featuresAr: ['مجمع سكني', 'مسبح', 'صالة رياضية', 'ملعب تنس', 'أمن على مدار الساعة'],
    isFeatured: true,
  },
  {
    title: 'Factory in Jubail Industrial',
    titleAr: 'مصنع في الجبيل الصناعية',
    description: 'Large factory facility with all utilities. Ideal for manufacturing operations.',
    descriptionAr: 'مصنع كبير مع جميع المرافق. مثالي لعمليات التصنيع.',
    type: 'factory',
    category: 'industrial',
    status: 'for_sale',
    price: 8500000,
    currency: 'SAR',
    area: 5000,
    location: {
      address: 'Jubail Industrial City',
      addressAr: 'مدينة الجبيل الصناعية',
      city: 'Jubail',
      cityAr: 'الجبيل',
      country: 'Saudi Arabia',
      countryAr: 'السعودية',
      coordinates: { type: 'Point', coordinates: [49.6225, 27.0046] },
    },
    images: ['https://images.unsplash.com/photo-1565793298595-6a879b1d9492?w=800'],
    features: ['Heavy Power', 'Water Supply', 'Loading Area', 'Office', 'Worker Housing'],
    featuresAr: ['كهرباء صناعية', 'إمداد مياه', 'منطقة تحميل', 'مكتب', 'سكن عمال'],
    isFeatured: false,
  },
  {
    title: 'Modern Duplex in Al Rawdah',
    titleAr: 'دوبلكس حديث في الروضة',
    description: 'Beautiful duplex apartment with modern design and rooftop terrace.',
    descriptionAr: 'شقة دوبلكس جميلة بتصميم حديث وتراس على السطح.',
    type: 'apartment',
    category: 'residential',
    status: 'for_sale',
    price: 1800000,
    currency: 'SAR',
    area: 320,
    bedrooms: 4,
    bathrooms: 4,
    location: {
      address: 'Al Rawdah District',
      addressAr: 'حي الروضة',
      city: 'Jeddah',
      cityAr: 'جدة',
      country: 'Saudi Arabia',
      countryAr: 'السعودية',
      coordinates: { type: 'Point', coordinates: [39.1568, 21.5724] },
    },
    images: ['https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=800'],
    features: ['Duplex', 'Rooftop', 'Modern Design', 'Parking', 'Storage'],
    featuresAr: ['دوبلكس', 'سطح', 'تصميم حديث', 'موقف سيارات', 'مخزن'],
    isFeatured: false,
  },
  {
    title: 'Investment Land in NEOM',
    titleAr: 'أرض استثمارية في نيوم',
    description: 'Prime investment opportunity in NEOM. Strategic location for future development.',
    descriptionAr: 'فرصة استثمارية متميزة في نيوم. موقع استراتيجي للتطوير المستقبلي.',
    type: 'land',
    category: 'residential',
    status: 'for_sale',
    price: 5000000,
    currency: 'SAR',
    area: 2000,
    location: {
      address: 'NEOM Bay',
      addressAr: 'خليج نيوم',
      city: 'NEOM',
      cityAr: 'نيوم',
      country: 'Saudi Arabia',
      countryAr: 'السعودية',
      coordinates: { type: 'Point', coordinates: [35.0, 28.0] },
    },
    images: ['https://images.unsplash.com/photo-1518623489648-a173ef7824f3?w=800'],
    features: ['Sea View', 'Investment Zone', 'Future City', 'Strategic Location'],
    featuresAr: ['إطلالة بحرية', 'منطقة استثمارية', 'مدينة المستقبل', 'موقع استراتيجي'],
    isFeatured: true,
  },
  {
    title: 'Retail Shop in Al Andalus Mall',
    titleAr: 'محل تجاري في الأندلس مول',
    description: 'Prime retail space in busy shopping mall. High foot traffic location.',
    descriptionAr: 'مساحة تجارية متميزة في مول تجاري مزدحم. موقع ذو حركة عالية.',
    type: 'office',
    category: 'commercial',
    status: 'for_rent',
    price: 12000,
    currency: 'SAR',
    area: 80,
    location: {
      address: 'Al Andalus Mall',
      addressAr: 'الأندلس مول',
      city: 'Jeddah',
      cityAr: 'جدة',
      country: 'Saudi Arabia',
      countryAr: 'السعودية',
      coordinates: { type: 'Point', coordinates: [39.1256, 21.5891] },
    },
    images: ['https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=800'],
    features: ['Mall Location', 'High Traffic', 'AC', 'Security'],
    featuresAr: ['موقع في مول', 'حركة عالية', 'تكييف', 'أمن'],
    isFeatured: false,
  },
  {
    title: 'Compound Villa in Al Hamra',
    titleAr: 'فيلا في مجمع الحمراء',
    description: 'Family villa in secure compound with shared amenities and children play area.',
    descriptionAr: 'فيلا عائلية في مجمع آمن مع مرافق مشتركة ومنطقة لعب للأطفال.',
    type: 'villa',
    category: 'residential',
    status: 'for_rent',
    price: 95000,
    currency: 'SAR',
    area: 400,
    bedrooms: 4,
    bathrooms: 4,
    location: {
      address: 'Al Hamra Compound',
      addressAr: 'مجمع الحمراء',
      city: 'Riyadh',
      cityAr: 'الرياض',
      country: 'Saudi Arabia',
      countryAr: 'السعودية',
      coordinates: { type: 'Point', coordinates: [46.7012, 24.7234] },
    },
    images: ['https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800'],
    features: ['Compound', 'Pool', 'Gym', 'Playground', 'Security'],
    featuresAr: ['مجمع', 'مسبح', 'صالة رياضية', 'ملعب أطفال', 'أمن'],
    isFeatured: false,
  },
  {
    title: 'Serviced Apartment in Tahlia',
    titleAr: 'شقة فندقية في التحلية',
    description: 'Fully serviced apartment with hotel amenities. Perfect for business travelers.',
    descriptionAr: 'شقة فندقية بخدمات كاملة ومرافق فندقية. مثالية لرجال الأعمال.',
    type: 'apartment',
    category: 'residential',
    status: 'for_rent',
    price: 6000,
    currency: 'SAR',
    area: 75,
    bedrooms: 1,
    bathrooms: 1,
    location: {
      address: 'Tahlia Street',
      addressAr: 'شارع التحلية',
      city: 'Jeddah',
      cityAr: 'جدة',
      country: 'Saudi Arabia',
      countryAr: 'السعودية',
      coordinates: { type: 'Point', coordinates: [39.1345, 21.5867] },
    },
    images: ['https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800'],
    features: ['Serviced', 'Furnished', 'Room Service', 'Gym', 'Pool'],
    featuresAr: ['خدمات فندقية', 'مفروش', 'خدمة غرف', 'صالة رياضية', 'مسبح'],
    isFeatured: false,
  },
  {
    title: 'Medical Center Building',
    titleAr: 'مبنى مركز طبي',
    description: 'Purpose-built medical center with clinic spaces and pharmacy areas.',
    descriptionAr: 'مركز طبي مبني خصيصاً مع مساحات عيادات ومناطق صيدليات.',
    type: 'building',
    category: 'commercial',
    status: 'for_sale',
    price: 22000000,
    currency: 'SAR',
    area: 4500,
    location: {
      address: 'King Fahd Road',
      addressAr: 'طريق الملك فهد',
      city: 'Riyadh',
      cityAr: 'الرياض',
      country: 'Saudi Arabia',
      countryAr: 'السعودية',
      coordinates: { type: 'Point', coordinates: [46.7112, 24.7456] },
    },
    images: ['https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?w=800'],
    features: ['Medical Use', 'Elevator', 'Parking', 'Generator', 'Central AC'],
    featuresAr: ['استخدام طبي', 'مصعد', 'موقف سيارات', 'مولد كهربائي', 'تكييف مركزي'],
    isFeatured: false,
  },
  {
    title: 'Traditional House in Al Balad',
    titleAr: 'بيت تراثي في البلد',
    description: 'Restored traditional house in historic Jeddah. Unique architectural heritage.',
    descriptionAr: 'بيت تراثي مرمم في جدة التاريخية. تراث معماري فريد.',
    type: 'villa',
    category: 'residential',
    status: 'for_sale',
    price: 6500000,
    currency: 'SAR',
    area: 500,
    bedrooms: 5,
    bathrooms: 4,
    location: {
      address: 'Al Balad Historic District',
      addressAr: 'حي البلد التاريخي',
      city: 'Jeddah',
      cityAr: 'جدة',
      country: 'Saudi Arabia',
      countryAr: 'السعودية',
      coordinates: { type: 'Point', coordinates: [39.1867, 21.4858] },
    },
    images: ['https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800'],
    features: ['Historic', 'Restored', 'Traditional Architecture', 'Courtyard'],
    featuresAr: ['تاريخي', 'مرمم', 'عمارة تقليدية', 'فناء'],
    isFeatured: true,
  },
];

async function seed() {
  try {
    console.log('🌱 Starting database seed...');

    // Connect to MongoDB
    await mongoose.connect(config.mongoUri);
    console.log('📦 Connected to MongoDB');

    // Create demo user if not exists
    let demoUser = await User.findOne({ email: 'demo@upgreat.com' });

    if (!demoUser) {
      // Don't hash password manually - the User model's pre-save hook does it
      demoUser = await User.create({
        email: 'demo@upgreat.com',
        password: 'Demo123!',
        fullName: 'Demo User',
        fullNameAr: 'مستخدم تجريبي',
        role: 'owner',
        isActive: true,
        isVerified: true,
      });
      console.log('👤 Created demo user: demo@upgreat.com / Demo123!');
    } else {
      // Update password in case it was double-hashed
      demoUser.password = 'Demo123!';
      await demoUser.save();
      console.log('👤 Demo user password reset');
    }

    // Clear existing properties
    await Property.deleteMany({});
    console.log('🗑️  Cleared existing properties');

    // Insert sample properties
    const propertiesWithOwner = sampleProperties.map((p) => ({
      ...p,
      owner: demoUser!._id,
      viewCount: Math.floor(Math.random() * 200) + 50,
    }));

    await Property.insertMany(propertiesWithOwner);
    console.log(`✅ Inserted ${sampleProperties.length} sample properties`);

    console.log('');
    console.log('🎉 Seed completed successfully!');
    console.log('');
    console.log('Demo Account:');
    console.log('  Email: demo@upgreat.com');
    console.log('  Password: Demo123!');
    console.log('');

    await mongoose.disconnect();
    process.exit(0);
  } catch (error) {
    console.error('❌ Seed failed:', error);
    process.exit(1);
  }
}

seed();
