import mongoose from 'mongoose';
import { config } from './config/index.js';
import User from './models/User.js';
import Property from './models/Property.js';

// Sample properties data
const sampleProperties = [
  {
    title: 'Luxury Villa in Riyadh',
    titleAr: 'فيلا فاخرة في الرياض',
    description:
      'Beautiful 5-bedroom villa with private pool, garden, and modern amenities. Located in the prestigious Al Olaya district.',
    descriptionAr:
      'فيلا جميلة من 5 غرف نوم مع مسبح خاص وحديقة ومرافق حديثة. تقع في حي العليا المرموق.',
    type: 'villa',
    category: 'residential',
    status: 'for_sale',
    price: 2500000,
    currency: 'SAR',
    area: 450,
    bedrooms: 5,
    bathrooms: 4,
    location: {
      address: 'Al Olaya District',
      addressAr: 'حي العليا',
      city: 'Riyadh',
      cityAr: 'الرياض',
      country: 'Saudi Arabia',
      countryAr: 'السعودية',
      coordinates: { type: 'Point', coordinates: [46.6753, 24.7136] },
    },
    images: ['https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800'],
    features: ['Pool', 'Garden', 'Garage', 'Smart Home', 'Security System'],
    featuresAr: ['مسبح', 'حديقة', 'كراج', 'منزل ذكي', 'نظام أمان'],
    isFeatured: true,
  },
  {
    title: 'Modern Apartment in Jeddah',
    titleAr: 'شقة حديثة في جدة',
    description:
      'Stunning sea view apartment with 3 bedrooms. Features modern finishes and access to building amenities.',
    descriptionAr: 'شقة مطلة على البحر مع 3 غرف نوم. تتميز بتشطيبات حديثة ووصول إلى مرافق المبنى.',
    type: 'apartment',
    category: 'residential',
    status: 'for_rent',
    price: 8000,
    currency: 'SAR',
    area: 180,
    bedrooms: 3,
    bathrooms: 2,
    location: {
      address: 'Corniche Road',
      addressAr: 'طريق الكورنيش',
      city: 'Jeddah',
      cityAr: 'جدة',
      country: 'Saudi Arabia',
      countryAr: 'السعودية',
      coordinates: { type: 'Point', coordinates: [39.1728, 21.5433] },
    },
    images: ['https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800'],
    features: ['Sea View', 'Gym', 'Parking', 'Concierge', 'Balcony'],
    featuresAr: ['إطلالة بحرية', 'صالة رياضية', 'موقف سيارات', 'خدمة استقبال', 'شرفة'],
    isFeatured: true,
  },
  {
    title: 'Office Space in KAFD',
    titleAr: 'مكتب في كافد',
    description:
      'Premium office space in the King Abdullah Financial District. Perfect for businesses looking for a prestigious address.',
    descriptionAr:
      'مساحة مكتبية متميزة في مركز الملك عبدالله المالي. مثالية للشركات التي تبحث عن عنوان مرموق.',
    type: 'office',
    category: 'commercial',
    status: 'for_rent',
    price: 15000,
    currency: 'SAR',
    area: 250,
    location: {
      address: 'King Abdullah Financial District',
      addressAr: 'مركز الملك عبدالله المالي',
      city: 'Riyadh',
      cityAr: 'الرياض',
      country: 'Saudi Arabia',
      countryAr: 'السعودية',
      coordinates: { type: 'Point', coordinates: [46.6396, 24.7648] },
    },
    images: ['https://images.unsplash.com/photo-1497366216548-37526070297c?w=800'],
    features: ['Meeting Rooms', '24/7 Access', 'Parking', 'High-Speed Internet', 'Reception'],
    featuresAr: [
      'قاعات اجتماعات',
      'دخول على مدار الساعة',
      'موقف سيارات',
      'إنترنت عالي السرعة',
      'استقبال',
    ],
    isFeatured: true,
  },
  {
    title: 'Land Plot in Al Khobar',
    titleAr: 'أرض في الخبر',
    description:
      'Prime residential land plot in Al Khobar. Ideal for building your dream home or investment.',
    descriptionAr: 'قطعة أرض سكنية متميزة في الخبر. مثالية لبناء منزل أحلامك أو الاستثمار.',
    type: 'land',
    category: 'residential',
    status: 'for_sale',
    price: 800000,
    currency: 'SAR',
    area: 600,
    location: {
      address: 'Al Rawabi District',
      addressAr: 'حي الروابي',
      city: 'Al Khobar',
      cityAr: 'الخبر',
      country: 'Saudi Arabia',
      countryAr: 'السعودية',
      coordinates: { type: 'Point', coordinates: [50.2083, 26.2794] },
    },
    images: ['https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800'],
    features: ['Corner Plot', 'Near Schools', 'Near Mosque', 'Paved Roads'],
    featuresAr: ['قطعة زاوية', 'قرب المدارس', 'قرب المسجد', 'شوارع مسفلتة'],
    isFeatured: false,
  },
  {
    title: 'Warehouse in Dammam Industrial',
    titleAr: 'مستودع في دمام الصناعية',
    description:
      'Large warehouse facility with loading docks and office space. Perfect for logistics operations.',
    descriptionAr: 'مستودع كبير مع أرصفة تحميل ومساحة مكتبية. مثالي لعمليات الخدمات اللوجستية.',
    type: 'warehouse',
    category: 'industrial',
    status: 'for_rent',
    price: 25000,
    currency: 'SAR',
    area: 2000,
    location: {
      address: 'Second Industrial City',
      addressAr: 'المدينة الصناعية الثانية',
      city: 'Dammam',
      cityAr: 'الدمام',
      country: 'Saudi Arabia',
      countryAr: 'السعودية',
      coordinates: { type: 'Point', coordinates: [50.0028, 26.3927] },
    },
    images: ['https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=800'],
    features: ['Loading Docks', 'Office Space', 'High Ceiling', '24/7 Security', 'Fire System'],
    featuresAr: ['أرصفة تحميل', 'مساحة مكتبية', 'سقف عالي', 'أمان على مدار الساعة', 'نظام إطفاء'],
    isFeatured: false,
  },
  {
    title: 'Penthouse in King Abdullah Economic City',
    titleAr: 'بنتهاوس في مدينة الملك عبدالله الاقتصادية',
    description:
      'Exclusive penthouse with panoramic views. Features private terrace, jacuzzi, and premium finishes.',
    descriptionAr: 'بنتهاوس حصري مع إطلالات بانورامية. يتميز بتراس خاص وجاكوزي وتشطيبات فاخرة.',
    type: 'apartment',
    category: 'residential',
    status: 'for_sale',
    price: 3500000,
    currency: 'SAR',
    area: 350,
    bedrooms: 4,
    bathrooms: 5,
    location: {
      address: 'Bay La Sun',
      addressAr: 'باي لاسن',
      city: 'King Abdullah Economic City',
      cityAr: 'مدينة الملك عبدالله الاقتصادية',
      country: 'Saudi Arabia',
      countryAr: 'السعودية',
      coordinates: { type: 'Point', coordinates: [39.1282, 22.4532] },
    },
    images: ['https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800'],
    features: ['Private Terrace', 'Jacuzzi', 'Smart Home', 'Private Elevator', 'Sea View'],
    featuresAr: ['تراس خاص', 'جاكوزي', 'منزل ذكي', 'مصعد خاص', 'إطلالة بحرية'],
    isFeatured: true,
  },
  // Additional properties
  {
    title: 'Cozy Studio in Al Malaz',
    titleAr: 'استوديو مريح في الملز',
    description:
      'Perfect starter apartment with modern kitchen and bathroom. Close to public transport and shopping.',
    descriptionAr: 'شقة مثالية للمبتدئين مع مطبخ وحمام حديث. قريبة من وسائل النقل العام والتسوق.',
    type: 'apartment',
    category: 'residential',
    status: 'for_rent',
    price: 2500,
    currency: 'SAR',
    area: 45,
    bedrooms: 1,
    bathrooms: 1,
    location: {
      address: 'Al Malaz District',
      addressAr: 'حي الملز',
      city: 'Riyadh',
      cityAr: 'الرياض',
      country: 'Saudi Arabia',
      countryAr: 'السعودية',
      coordinates: { type: 'Point', coordinates: [46.7219, 24.6748] },
    },
    images: ['https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800'],
    features: ['Furnished', 'AC', 'Kitchen', 'Near Metro'],
    featuresAr: ['مفروش', 'مكيف', 'مطبخ', 'قرب المترو'],
    isFeatured: false,
  },
  {
    title: 'Family Villa in Al Nakheel',
    titleAr: 'فيلا عائلية في النخيل',
    description:
      'Spacious family villa with 6 bedrooms, large garden, and swimming pool. Perfect for large families.',
    descriptionAr: 'فيلا عائلية واسعة مع 6 غرف نوم وحديقة كبيرة ومسبح. مثالية للعائلات الكبيرة.',
    type: 'villa',
    category: 'residential',
    status: 'for_sale',
    price: 4200000,
    currency: 'SAR',
    area: 650,
    bedrooms: 6,
    bathrooms: 5,
    location: {
      address: 'Al Nakheel District',
      addressAr: 'حي النخيل',
      city: 'Riyadh',
      cityAr: 'الرياض',
      country: 'Saudi Arabia',
      countryAr: 'السعودية',
      coordinates: { type: 'Point', coordinates: [46.6289, 24.7743] },
    },
    images: ['https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800'],
    features: ['Pool', 'Garden', 'Maid Room', 'Driver Room', 'Garage'],
    featuresAr: ['مسبح', 'حديقة', 'غرفة خادمة', 'غرفة سائق', 'كراج'],
    isFeatured: true,
  },
  {
    title: 'Commercial Building in Olaya',
    titleAr: 'مبنى تجاري في العليا',
    description:
      'Prime commercial building with multiple floors. Excellent location for retail or office use.',
    descriptionAr: 'مبنى تجاري متميز متعدد الطوابق. موقع ممتاز للبيع بالتجزئة أو المكاتب.',
    type: 'building',
    category: 'commercial',
    status: 'for_sale',
    price: 15000000,
    currency: 'SAR',
    area: 3500,
    location: {
      address: 'Olaya Street',
      addressAr: 'شارع العليا',
      city: 'Riyadh',
      cityAr: 'الرياض',
      country: 'Saudi Arabia',
      countryAr: 'السعودية',
      coordinates: { type: 'Point', coordinates: [46.685, 24.6916] },
    },
    images: ['https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=800'],
    features: ['Elevator', 'Parking', 'Central AC', 'Security', 'Reception'],
    featuresAr: ['مصعد', 'موقف سيارات', 'تكييف مركزي', 'أمن', 'استقبال'],
    isFeatured: true,
  },
  {
    title: 'Beachfront Chalet in Half Moon Bay',
    titleAr: 'شاليه على البحر في خليج نصف القمر',
    description: 'Stunning beachfront chalet with direct beach access. Perfect weekend getaway.',
    descriptionAr: 'شاليه رائع على الشاطئ مع وصول مباشر للبحر. مثالي لعطلة نهاية الأسبوع.',
    type: 'villa',
    category: 'residential',
    status: 'for_rent',
    price: 5000,
    currency: 'SAR',
    area: 200,
    bedrooms: 3,
    bathrooms: 2,
    location: {
      address: 'Half Moon Bay',
      addressAr: 'خليج نصف القمر',
      city: 'Al Khobar',
      cityAr: 'الخبر',
      country: 'Saudi Arabia',
      countryAr: 'السعودية',
      coordinates: { type: 'Point', coordinates: [50.0567, 26.1833] },
    },
    images: ['https://images.unsplash.com/photo-1499793983690-e29da59ef1c2?w=800'],
    features: ['Beach Access', 'BBQ Area', 'Furnished', 'Parking'],
    featuresAr: ['وصول للشاطئ', 'منطقة شواء', 'مفروش', 'موقف سيارات'],
    isFeatured: false,
  },
  {
    title: 'Luxury Apartment in Diplomatic Quarter',
    titleAr: 'شقة فاخرة في الحي الدبلوماسي',
    description: 'High-end apartment in the prestigious Diplomatic Quarter with premium amenities.',
    descriptionAr: 'شقة راقية في الحي الدبلوماسي المرموق مع مرافق متميزة.',
    type: 'apartment',
    category: 'residential',
    status: 'for_rent',
    price: 18000,
    currency: 'SAR',
    area: 280,
    bedrooms: 4,
    bathrooms: 3,
    location: {
      address: 'Diplomatic Quarter',
      addressAr: 'الحي الدبلوماسي',
      city: 'Riyadh',
      cityAr: 'الرياض',
      country: 'Saudi Arabia',
      countryAr: 'السعودية',
      coordinates: { type: 'Point', coordinates: [46.6162, 24.6856] },
    },
    images: ['https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800'],
    features: ['Compound', 'Pool', 'Gym', 'Tennis Court', '24/7 Security'],
    featuresAr: ['مجمع سكني', 'مسبح', 'صالة رياضية', 'ملعب تنس', 'أمن على مدار الساعة'],
    isFeatured: true,
  },
  {
    title: 'Factory in Jubail Industrial',
    titleAr: 'مصنع في الجبيل الصناعية',
    description: 'Large factory facility with all utilities. Ideal for manufacturing operations.',
    descriptionAr: 'مصنع كبير مع جميع المرافق. مثالي لعمليات التصنيع.',
    type: 'factory',
    category: 'industrial',
    status: 'for_sale',
    price: 8500000,
    currency: 'SAR',
    area: 5000,
    location: {
      address: 'Jubail Industrial City',
      addressAr: 'مدينة الجبيل الصناعية',
      city: 'Jubail',
      cityAr: 'الجبيل',
      country: 'Saudi Arabia',
      countryAr: 'السعودية',
      coordinates: { type: 'Point', coordinates: [49.6225, 27.0046] },
    },
    images: ['https://images.unsplash.com/photo-1565793298595-6a879b1d9492?w=800'],
    features: ['Heavy Power', 'Water Supply', 'Loading Area', 'Office', 'Worker Housing'],
    featuresAr: ['كهرباء صناعية', 'إمداد مياه', 'منطقة تحميل', 'مكتب', 'سكن عمال'],
    isFeatured: false,
  },
  {
    title: 'Modern Duplex in Al Rawdah',
    titleAr: 'دوبلكس حديث في الروضة',
    description: 'Beautiful duplex apartment with modern design and rooftop terrace.',
    descriptionAr: 'شقة دوبلكس جميلة بتصميم حديث وتراس على السطح.',
    type: 'apartment',
    category: 'residential',
    status: 'for_sale',
    price: 1800000,
    currency: 'SAR',
    area: 320,
    bedrooms: 4,
    bathrooms: 4,
    location: {
      address: 'Al Rawdah District',
      addressAr: 'حي الروضة',
      city: 'Jeddah',
      cityAr: 'جدة',
      country: 'Saudi Arabia',
      countryAr: 'السعودية',
      coordinates: { type: 'Point', coordinates: [39.1568, 21.5724] },
    },
    images: ['https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=800'],
    features: ['Duplex', 'Rooftop', 'Modern Design', 'Parking', 'Storage'],
    featuresAr: ['دوبلكس', 'سطح', 'تصميم حديث', 'موقف سيارات', 'مخزن'],
    isFeatured: false,
  },
  {
    title: 'Investment Land in NEOM',
    titleAr: 'أرض استثمارية في نيوم',
    description: 'Prime investment opportunity in NEOM. Strategic location for future development.',
    descriptionAr: 'فرصة استثمارية متميزة في نيوم. موقع استراتيجي للتطوير المستقبلي.',
    type: 'land',
    category: 'residential',
    status: 'for_sale',
    price: 5000000,
    currency: 'SAR',
    area: 2000,
    location: {
      address: 'NEOM Bay',
      addressAr: 'خليج نيوم',
      city: 'NEOM',
      cityAr: 'نيوم',
      country: 'Saudi Arabia',
      countryAr: 'السعودية',
      coordinates: { type: 'Point', coordinates: [35.0, 28.0] },
    },
    images: ['https://images.unsplash.com/photo-1518623489648-a173ef7824f3?w=800'],
    features: ['Sea View', 'Investment Zone', 'Future City', 'Strategic Location'],
    featuresAr: ['إطلالة بحرية', 'منطقة استثمارية', 'مدينة المستقبل', 'موقع استراتيجي'],
    isFeatured: true,
  },
  {
    title: 'Retail Shop in Al Andalus Mall',
    titleAr: 'محل تجاري في الأندلس مول',
    description: 'Prime retail space in busy shopping mall. High foot traffic location.',
    descriptionAr: 'مساحة تجارية متميزة في مول تجاري مزدحم. موقع ذو حركة عالية.',
    type: 'office',
    category: 'commercial',
    status: 'for_rent',
    price: 12000,
    currency: 'SAR',
    area: 80,
    location: {
      address: 'Al Andalus Mall',
      addressAr: 'الأندلس مول',
      city: 'Jeddah',
      cityAr: 'جدة',
      country: 'Saudi Arabia',
      countryAr: 'السعودية',
      coordinates: { type: 'Point', coordinates: [39.1256, 21.5891] },
    },
    images: ['https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=800'],
    features: ['Mall Location', 'High Traffic', 'AC', 'Security'],
    featuresAr: ['موقع في مول', 'حركة عالية', 'تكييف', 'أمن'],
    isFeatured: false,
  },
  {
    title: 'Compound Villa in Al Hamra',
    titleAr: 'فيلا في مجمع الحمراء',
    description: 'Family villa in secure compound with shared amenities and children play area.',
    descriptionAr: 'فيلا عائلية في مجمع آمن مع مرافق مشتركة ومنطقة لعب للأطفال.',
    type: 'villa',
    category: 'residential',
    status: 'for_rent',
    price: 95000,
    currency: 'SAR',
    area: 400,
    bedrooms: 4,
    bathrooms: 4,
    location: {
      address: 'Al Hamra Compound',
      addressAr: 'مجمع الحمراء',
      city: 'Riyadh',
      cityAr: 'الرياض',
      country: 'Saudi Arabia',
      countryAr: 'السعودية',
      coordinates: { type: 'Point', coordinates: [46.7012, 24.7234] },
    },
    images: ['https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800'],
    features: ['Compound', 'Pool', 'Gym', 'Playground', 'Security'],
    featuresAr: ['مجمع', 'مسبح', 'صالة رياضية', 'ملعب أطفال', 'أمن'],
    isFeatured: false,
  },
  {
    title: 'Serviced Apartment in Tahlia',
    titleAr: 'شقة فندقية في التحلية',
    description: 'Fully serviced apartment with hotel amenities. Perfect for business travelers.',
    descriptionAr: 'شقة فندقية بخدمات كاملة ومرافق فندقية. مثالية لرجال الأعمال.',
    type: 'apartment',
    category: 'residential',
    status: 'for_rent',
    price: 6000,
    currency: 'SAR',
    area: 75,
    bedrooms: 1,
    bathrooms: 1,
    location: {
      address: 'Tahlia Street',
      addressAr: 'شارع التحلية',
      city: 'Jeddah',
      cityAr: 'جدة',
      country: 'Saudi Arabia',
      countryAr: 'السعودية',
      coordinates: { type: 'Point', coordinates: [39.1345, 21.5867] },
    },
    images: ['https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800'],
    features: ['Serviced', 'Furnished', 'Room Service', 'Gym', 'Pool'],
    featuresAr: ['خدمات فندقية', 'مفروش', 'خدمة غرف', 'صالة رياضية', 'مسبح'],
    isFeatured: false,
  },
  {
    title: 'Medical Center Building',
    titleAr: 'مبنى مركز طبي',
    description: 'Purpose-built medical center with clinic spaces and pharmacy areas.',
    descriptionAr: 'مركز طبي مبني خصيصاً مع مساحات عيادات ومناطق صيدليات.',
    type: 'building',
    category: 'commercial',
    status: 'for_sale',
    price: 22000000,
    currency: 'SAR',
    area: 4500,
    location: {
      address: 'King Fahd Road',
      addressAr: 'طريق الملك فهد',
      city: 'Riyadh',
      cityAr: 'الرياض',
      country: 'Saudi Arabia',
      countryAr: 'السعودية',
      coordinates: { type: 'Point', coordinates: [46.7112, 24.7456] },
    },
    images: ['https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?w=800'],
    features: ['Medical Use', 'Elevator', 'Parking', 'Generator', 'Central AC'],
    featuresAr: ['استخدام طبي', 'مصعد', 'موقف سيارات', 'مولد كهربائي', 'تكييف مركزي'],
    isFeatured: false,
  },
  {
    title: 'Traditional House in Al Balad',
    titleAr: 'بيت تراثي في البلد',
    description: 'Restored traditional house in historic Jeddah. Unique architectural heritage.',
    descriptionAr: 'بيت تراثي مرمم في جدة التاريخية. تراث معماري فريد.',
    type: 'villa',
    category: 'residential',
    status: 'for_sale',
    price: 6500000,
    currency: 'SAR',
    area: 500,
    bedrooms: 5,
    bathrooms: 4,
    location: {
      address: 'Al Balad Historic District',
      addressAr: 'حي البلد التاريخي',
      city: 'Jeddah',
      cityAr: 'جدة',
      country: 'Saudi Arabia',
      countryAr: 'السعودية',
      coordinates: { type: 'Point', coordinates: [39.1867, 21.4858] },
    },
    images: ['https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800'],
    features: ['Historic', 'Restored', 'Traditional Architecture', 'Courtyard'],
    featuresAr: ['تاريخي', 'مرمم', 'عمارة تقليدية', 'فناء'],
    isFeatured: true,
  },
  // Additional properties to reach 25+
  {
    title: 'Smart Home Villa in Al Yasmin',
    titleAr: 'فيلا ذكية في الياسمين',
    description:
      'Ultra-modern smart home with automated systems, solar panels, and sustainable design.',
    descriptionAr: 'منزل ذكي حديث للغاية مع أنظمة آلية وألواح شمسية وتصميم مستدام.',
    type: 'villa',
    category: 'residential',
    status: 'for_sale',
    price: 5500000,
    currency: 'SAR',
    area: 550,
    bedrooms: 5,
    bathrooms: 6,
    location: {
      address: 'Al Yasmin District',
      addressAr: 'حي الياسمين',
      city: 'Riyadh',
      cityAr: 'الرياض',
      country: 'Saudi Arabia',
      countryAr: 'السعودية',
      coordinates: { type: 'Point', coordinates: [46.6253, 24.8236] },
    },
    images: ['https://images.unsplash.com/photo-1558036117-15d82a90b9b1?w=800'],
    features: ['Smart Home', 'Solar Panels', 'EV Charging', 'Home Theater', 'Wine Cellar'],
    featuresAr: ['منزل ذكي', 'ألواح شمسية', 'شحن سيارات كهربائية', 'مسرح منزلي', 'قبو'],
    isFeatured: true,
  },
  {
    title: 'Executive Office Suite in Granada Mall',
    titleAr: 'مكتب تنفيذي في غرناطة مول',
    description:
      'Premium office suite in Granada Business Center with meeting rooms and reception.',
    descriptionAr: 'جناح مكتبي متميز في مركز غرناطة للأعمال مع قاعات اجتماعات واستقبال.',
    type: 'office',
    category: 'commercial',
    status: 'for_rent',
    price: 22000,
    currency: 'SAR',
    area: 300,
    location: {
      address: 'Granada Business Center',
      addressAr: 'مركز غرناطة للأعمال',
      city: 'Riyadh',
      cityAr: 'الرياض',
      country: 'Saudi Arabia',
      countryAr: 'السعودية',
      coordinates: { type: 'Point', coordinates: [46.7234, 24.7456] },
    },
    images: ['https://images.unsplash.com/photo-1497366216548-37526070297c?w=800'],
    features: ['Furnished', 'Meeting Rooms', 'Reception', 'Parking', 'Cafeteria Access'],
    featuresAr: ['مفروش', 'قاعات اجتماعات', 'استقبال', 'موقف سيارات', 'كافتيريا'],
    isFeatured: false,
  },
  {
    title: 'Waterfront Apartment in Obhur',
    titleAr: 'شقة على الواجهة البحرية في أبحر',
    description:
      'Stunning waterfront apartment with private beach access and panoramic Red Sea views.',
    descriptionAr:
      'شقة رائعة على الواجهة البحرية مع وصول خاص للشاطئ وإطلالات بانورامية على البحر الأحمر.',
    type: 'apartment',
    category: 'residential',
    status: 'for_sale',
    price: 2800000,
    currency: 'SAR',
    area: 220,
    bedrooms: 3,
    bathrooms: 3,
    location: {
      address: 'Obhur Waterfront',
      addressAr: 'واجهة أبحر البحرية',
      city: 'Jeddah',
      cityAr: 'جدة',
      country: 'Saudi Arabia',
      countryAr: 'السعودية',
      coordinates: { type: 'Point', coordinates: [39.0987, 21.7123] },
    },
    images: ['https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800'],
    features: ['Beach Access', 'Sea View', 'Pool', 'Gym', 'Concierge'],
    featuresAr: ['وصول للشاطئ', 'إطلالة بحرية', 'مسبح', 'صالة رياضية', 'خدمة استقبال'],
    isFeatured: true,
  },
  {
    title: 'Logistics Hub in Eastern Province',
    titleAr: 'مركز لوجستي في المنطقة الشرقية',
    description: 'Strategic logistics facility with cold storage, truck docks, and office space.',
    descriptionAr: 'مرفق لوجستي استراتيجي مع تخزين بارد ومرافق شحن ومساحة مكتبية.',
    type: 'warehouse',
    category: 'industrial',
    status: 'for_sale',
    price: 12000000,
    currency: 'SAR',
    area: 8000,
    location: {
      address: 'Industrial Zone, Dammam',
      addressAr: 'المنطقة الصناعية، الدمام',
      city: 'Dammam',
      cityAr: 'الدمام',
      country: 'Saudi Arabia',
      countryAr: 'السعودية',
      coordinates: { type: 'Point', coordinates: [50.1234, 26.4567] },
    },
    images: ['https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=800'],
    features: ['Cold Storage', 'Truck Docks', 'Office', '24/7 Security', 'Rail Access'],
    featuresAr: ['تخزين بارد', 'مرافق شحن', 'مكتب', 'أمن على مدار الساعة', 'وصول للسكك الحديدية'],
    isFeatured: false,
  },
  {
    title: 'Budget Apartment in Al Batha',
    titleAr: 'شقة اقتصادية في البطحاء',
    description:
      'Affordable apartment ideal for singles or small families. Close to public transport.',
    descriptionAr:
      'شقة بأسعار معقولة مثالية للأفراد أو العائلات الصغيرة. قريبة من المواصلات العامة.',
    type: 'apartment',
    category: 'residential',
    status: 'for_rent',
    price: 1500,
    currency: 'SAR',
    area: 60,
    bedrooms: 2,
    bathrooms: 1,
    location: {
      address: 'Al Batha District',
      addressAr: 'حي البطحاء',
      city: 'Riyadh',
      cityAr: 'الرياض',
      country: 'Saudi Arabia',
      countryAr: 'السعودية',
      coordinates: { type: 'Point', coordinates: [46.7145, 24.6345] },
    },
    images: ['https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=800'],
    features: ['AC', 'Kitchen', 'Near Metro', 'Shops Nearby'],
    featuresAr: ['مكيف', 'مطبخ', 'قرب المترو', 'محلات قريبة'],
    isFeatured: false,
  },
  {
    title: 'Golf Course Villa in KAEC',
    titleAr: 'فيلا على ملعب الغولف في كايك',
    description: 'Exclusive villa overlooking Royal Greens Golf Course with club membership.',
    descriptionAr: 'فيلا حصرية تطل على ملعب رويال غرينز للغولف مع عضوية النادي.',
    type: 'villa',
    category: 'residential',
    status: 'for_sale',
    price: 7500000,
    currency: 'SAR',
    area: 700,
    bedrooms: 6,
    bathrooms: 7,
    location: {
      address: 'Royal Greens, KAEC',
      addressAr: 'رويال غرينز، كايك',
      city: 'King Abdullah Economic City',
      cityAr: 'مدينة الملك عبدالله الاقتصادية',
      country: 'Saudi Arabia',
      countryAr: 'السعودية',
      coordinates: { type: 'Point', coordinates: [39.0654, 22.4123] },
    },
    images: ['https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800'],
    features: ['Golf View', 'Club Membership', 'Private Pool', 'Garden', 'Guest House'],
    featuresAr: ['إطلالة غولف', 'عضوية نادي', 'مسبح خاص', 'حديقة', 'بيت ضيافة'],
    isFeatured: true,
  },
  {
    title: 'Restaurant Space in Al Tahlia',
    titleAr: 'مساحة مطعم في التحلية',
    description: 'Prime restaurant location with outdoor seating area. High foot traffic zone.',
    descriptionAr: 'موقع مطعم متميز مع منطقة جلوس خارجية. منطقة ذات حركة مرور عالية.',
    type: 'office',
    category: 'commercial',
    status: 'for_rent',
    price: 35000,
    currency: 'SAR',
    area: 400,
    location: {
      address: 'Tahlia Street',
      addressAr: 'شارع التحلية',
      city: 'Riyadh',
      cityAr: 'الرياض',
      country: 'Saudi Arabia',
      countryAr: 'السعودية',
      coordinates: { type: 'Point', coordinates: [46.6789, 24.7012] },
    },
    images: ['https://images.unsplash.com/photo-1552566626-52f8b828add9?w=800'],
    features: ['Outdoor Seating', 'Commercial Kitchen', 'Parking', 'Storage', 'High Visibility'],
    featuresAr: ['جلوس خارجي', 'مطبخ تجاري', 'موقف سيارات', 'مخزن', 'رؤية عالية'],
    isFeatured: false,
  },
  {
    title: 'Residential Land in Diriyah',
    titleAr: 'أرض سكنية في الدرعية',
    description: 'Premium land near UNESCO heritage site. Perfect for heritage-style villa.',
    descriptionAr: 'أرض متميزة بالقرب من موقع التراث العالمي. مثالية لفيلا بطراز تراثي.',
    type: 'land',
    category: 'residential',
    status: 'for_sale',
    price: 3500000,
    currency: 'SAR',
    area: 1200,
    location: {
      address: 'Diriyah Gate',
      addressAr: 'بوابة الدرعية',
      city: 'Riyadh',
      cityAr: 'الرياض',
      country: 'Saudi Arabia',
      countryAr: 'السعودية',
      coordinates: { type: 'Point', coordinates: [46.5723, 24.7345] },
    },
    images: ['https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800'],
    features: [
      'Near Heritage Site',
      'Premium Location',
      'Investment Opportunity',
      'Development Ready',
    ],
    featuresAr: ['قرب موقع تراثي', 'موقع متميز', 'فرصة استثمارية', 'جاهز للتطوير'],
    isFeatured: true,
  },
];

// Demo users data
const demoUsers = [
  {
    email: 'buyer@upgreat.com',
    password: 'Demo123!',
    fullName: 'Ahmed Al-Buyer',
    fullNameAr: 'أحمد المشتري',
    phone: '+966501234567',
    role: 'buyer' as const,
    isActive: true,
    isVerified: true,
  },
  {
    email: 'owner@upgreat.com',
    password: 'Demo123!',
    fullName: 'Mohammed Al-Owner',
    fullNameAr: 'محمد المالك',
    phone: '+966502345678',
    role: 'owner' as const,
    isActive: true,
    isVerified: true,
  },
  {
    email: 'agent@upgreat.com',
    password: 'Demo123!',
    fullName: 'Sara Al-Agent',
    fullNameAr: 'سارة الوكيلة',
    phone: '+966503456789',
    role: 'agent' as const,
    isActive: true,
    isVerified: true,
  },
  {
    email: 'admin@upgreat.com',
    password: 'Admin123!',
    fullName: 'Admin User',
    fullNameAr: 'مدير النظام',
    phone: '+966504567890',
    role: 'admin' as const,
    isActive: true,
    isVerified: true,
  },
];

async function seed() {
  try {
    console.log('🌱 Starting database seed...');

    // Connect to MongoDB
    await mongoose.connect(config.mongoUri);
    console.log('📦 Connected to MongoDB');

    // Create demo users
    const createdUsers: Record<string, (typeof demoUsers)[0] & { _id: unknown }> = {};

    for (const userData of demoUsers) {
      let user = await User.findOne({ email: userData.email });

      if (!user) {
        user = await User.create(userData);
        console.log(`👤 Created ${userData.role}: ${userData.email} / ${userData.password}`);
      } else {
        user.password = userData.password;
        await user.save();
        console.log(`👤 Reset password for ${userData.role}: ${userData.email}`);
      }

      createdUsers[userData.role] = { ...userData, _id: user._id };
    }

    // Clear existing properties
    await Property.deleteMany({});
    console.log('🗑️  Cleared existing properties');

    // Assign properties to different owners (owner and agent)
    const ownerIds = [createdUsers.owner._id, createdUsers.agent._id];
    const propertiesWithOwner = sampleProperties.map((p, index) => ({
      ...p,
      owner: ownerIds[index % ownerIds.length],
      viewCount: Math.floor(Math.random() * 200) + 50,
    }));

    await Property.insertMany(propertiesWithOwner);
    console.log(`✅ Inserted ${sampleProperties.length} sample properties`);

    console.log('');
    console.log('🎉 Seed completed successfully!');
    console.log('');
    console.log('Demo Accounts:');
    console.log('┌──────────────────────────────────────────────────┐');
    console.log('│ Role     │ Email                │ Password      │');
    console.log('├──────────────────────────────────────────────────┤');
    console.log('│ Buyer    │ buyer@upgreat.com    │ Demo123!      │');
    console.log('│ Owner    │ owner@upgreat.com    │ Demo123!      │');
    console.log('│ Agent    │ agent@upgreat.com    │ Demo123!      │');
    console.log('│ Admin    │ admin@upgreat.com    │ Admin123!     │');
    console.log('└──────────────────────────────────────────────────┘');
    console.log('');

    await mongoose.disconnect();
    process.exit(0);
  } catch (error) {
    console.error('❌ Seed failed:', error);
    process.exit(1);
  }
}

seed();
